---
version: '3'
services:
  dvwa:
    image: dvwa
    build:
      context: ./.
      dockerfile: dvwa.Dockerfile
    networks:
      main:
        aliases:
          - dvwa

  fast:
    image: wallarm/fast
    environment:
      WALLARM_API_TOKEN: waf1n4cJsQ7dIL7TthDfMueCe/MCSd7LBhCDgLVXvsO1YZ8w59tJUY6hUQbIXSZE
      WALLARM_API_HOST: us1.api.wallarm.com
      CI_MODE: recording
      #TEST_RUN_POLICY_ID: 87
      ALLOWED_HOSTS: dvwa
    networks:
      main:
        aliases:
          - fast

  selenium:
    image: selenium/standalone-firefox:latest
    logging:
      driver: none
    environment:
      http_proxy: http://fast:8080
    networks:
      main:
        aliases:
          - selenium

  test:
    image: test
    build:
      context: ./.
      dockerfile: test.Dockerfile
    networks:
      main:

  start_db:
    image: start_db
    build:
      context: ./.
      dockerfile: start_db.Dockerfile
    networks:
      main:

networks:
  main:
